### ISSUE TITLE
Migration task list

### ISSUE THREAD

**Issue by luke-john** [plugorgau/plugorgau.github.io#4]
- [x] Home ([Welcome to PLUG](http://plug.org.au/home)) - timwhite
- [x] [About PLUG](http://plug.org.au/about) - timwhite
  - [x] [Committee](http://plug.org.au/about/committee) - JamesBromberger
  - [x] [Previous Committees](http://plug.org.au/about/committee/previous) - JamesBromberger
  - [x] [Historical Committee members](http://plug.org.au/about/committee/history) - JamesBromberger
  - [x] [Constitution](http://plug.org.au/Constitution) - JamesBromberger
    - [x] [PLUG Constitution 2010](http://plug.org.au/Constitution/2010) - JamesBromberger
    - [x] [PLUG Constitution 2010](http://constitution/2010) - JamesBromberger
    - [x] [Current Constitution](http://plug.org.au/Constitution/Current) - JamesBromberger
    - [x] [PLUG Constitution 2012](http://plug.org.au/Constitution/2012) - Alastair
    - [x] [Important PLUG Documents](http://plug.org.au/about/documents) - JamesBromberger
    - [x] [Proposed Constitution 2012 Notes](http://plug.org.au/Constitution/Proposed2012Notes) - JamesBromberger
  - [x] [PLUG Documents and records](http://about/documents) - JamesBromberger
- [x] Sponsors
  - [x] [PLUG Sponsors](http://plug.org.au/sponsors) - timwhite
  - [x] [Hall of Fame](http://plug.org.au/sponsors/hall-of-fame) - JasonNicholls
- [ ] Get Involved
  - [x] [PLUG Mailing List](http://plug.org.au/resources/mailing-list) - JasonNicholls
  - [x] [Membership & Donations](http://plug.org.au/membership) - timwhite
- Services
  - [ ] [Newsletters](http://plug.org.au/resources/newsletters) - JamesBromberger
  - [ ] [PLUG Shell Accounts](http://plug.org.au/resources/shell-account) - JasonNicholls
- [ ] [Events](http://plug.org.au/events) - JamesBromberger
  - [ ] [Event Scheduling](http://plug.org.au/events/future) - JamesBromberger
  - other
    - [ ] [Software Freedom Day 2012](http://plug.org.au/events/SFD) - luke
    - [ ] [PLUG Logo Competition](http://plug.org.au/logo) - TimBowden
    - [ ] [2011 PLUG Quiz Night](http://plug.org.au/events/2011/Quiz_Night) - JamesBromberger
  - monthly meetings
    - [ ] [2002 Events](http://plug.org.au/events/2002) - JamesBromberger
    - [ ] [2003 Events](http://plug.org.au/events/2003) - JamesBromberger
    - [ ] [2004 Events](http://plug.org.au/events/2004) - JamesBromberger
    - [ ] [2005 Events](http://plug.org.au/events/2005) - JamesBromberger
    - [ ] [2006 Events](http://plug.org.au/events/2006) - JamesBromberger
    - [ ] [2007 Events](http://plug.org.au/events/2007) - JamesBromberger
    - [ ] [2008 Events](http://plug.org.au/events/2008) - JamesBromberger
    - [ ] [2009 Events](http://plug.org.au/events/2009) - JamesBromberger
    - [ ] [2010 Events](http://plug.org.au/events/2010) - JamesBromberger
    - [ ] [2011 Events](http://plug.org.au/events/2011) - JamesBromberger
    - [ ] [2012 Events](http://plug.org.au/events/2012) - JamesBromberger
  - [ ] [Annual General Meetings](http://plug.org.au/events/AGM) - JamesBromberger
    - [ ] [PLUG Annual General Meeting 2002](http://plug.org.au/events/AGM/2002) - JamesBromberger
    - [ ] [PLUG Annual General meeting 2003](http://plug.org.au/events/AGM/2003) - JamesBromberger
    - [ ] [Annual General Meeting Report 2004](http://plug.org.au/events/AGM/2004) - JamesBromberger
    - [ ] [PLUG Annual General Meeting, 2005](http://plug.org.au/events/AGM/2005) - JamesBromberger
    - [ ] [PLUG Annual General Meeting, 2006](http://plug.org.au/events/AGM/2006) - JamesBromberger
    - [ ] [PLUG Annual General Meeting, 2007](http://plug.org.au/events/AGM/2007) - JamesBromberger
    - [ ] [PLUG Annual General Meeting, 2008](http://plug.org.au/events/AGM/2008) - JamesBromberger
    - [ ] [PLUG Annual General Meeting, 2009](http://plug.org.au/events/AGM/2009) - JamesBromberger
    - [ ] [PLUG Annual General Meeting, 2009](http://events/AGM/2009) - JamesBromberger
    - [ ] [AGM Minutes 2010](http://plug.org.au/events/AGM/2010) - timwhite
    - [ ] [PLUG Annual General meeting, 2011](http://plug.org.au/events/AGM/2011) - JamesBromberger
- [x] [Projects](http://plug.org.au/projects) - JamesBromberger
  - [x] [Video Streaming Project](http://plug.org.au/projects/video) - JamesBromberger
    - [ ] [Setup Procedure](http://plug.org.au/projects/video/setupprocedure) - nickweb
    - [ ] [Physical Equipment](http://plug.org.au/projects/video/equipment) - JamesBromberger
    - [ ] [Video Streaming: Architectural Overview](http://plug.org.au/projects/video/architecture) - JamesBromberger
  - [ ] [Linux.conf.au Bid](http://plug.org.au/projects/userconf) - luke
  - [x] [User Group membership manager](http://plug.org.au/projects/ugmm) - JamesBromberger
- [ ] [Resources](http://plug.org.au/resources) - JasonNicholls
  - [ ] [Other Linux-related groups](http://plug.org.au/about/other-groups) - timwhite
  - [ ] [Getting Linux in Perth](http://plug.org.au/resources/linux) - JasonNicholls
  - [ ] [Branding and Marketing Materials](http://plug.org.au/resources/branding) - luke
  - [ ] [Other Groups & Events](http://plug.org.au/other_groups) - Anonymous
  - [ ] [IRC Server](http://plug.org.au/resources/irc) - luke
  - [ ] [Links](http://plug.org.au/resources/links) - JasonNicholls

**Comment by Zorlin** [comment]
This should all be complete, please open a new issue if you find anything missing.
